### PR TITLE
Create delayed_bots.gsc (fixes #76)

### LINKED ISSUE #76: [Feature Request] No bots until first player spawns
I would like to request two new variables:

- [ ] `bots_waitForFirstSpawn` Makes bots wait to join the server until the first player spawns, regardless of wether he's host or not.
- [ ] `bots_leaveAfterLastPlayer` Makes bots leave after the last player left the server, effectively ending the round (Maybe with an additional timedelay to allow for reconnects)

### PR DESCRIPTION
**Pull request by Bluscream**
This will make bots wait for the first player to spawn before spawning any bots. It works, but is very much a workaround and should not be merged as is. Instead a solution should be proposed so this functionality can be provided by via a dvar by the mod.

Related to #76

### CODE REVIEW

**Comment by Bluscream** [comment]
I also have https://github.com/xlabs-mirror/iw4-gsc-scripts/blob/main/scripts/mp/spawnoverride.gsc available which adds more spawns to SP maps

**Comment by ineedbots** [comment]
> I also have https://github.com/xlabs-mirror/iw4-gsc-scripts/blob/main/scripts/mp/spawnoverride.gsc available which adds more spawns to SP maps

mapents file would be the correct solution

**Comment by ineedbots** [comment]
I want this integrated into the scripts, not seperate, also the coding style is completely different. I will implement this.

**Comment by Bluscream** [comment]
> mapents file would be the correct solution

DDG does not know what that is https://duckduckgo.com/?q=mapents+file but sounds like something i could look into if i had some documentation

>  want this integrated into the scripts, not seperate, also the coding style is completely different. I will implement this.

thanks :)

**Pull request closed without merging**
